# Generated by Django 3.1.2 on 2020-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20201014_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picture_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
