# Generated by Django 3.1.2 on 2021-02-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20201229_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['numeration'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='picture_index',
            new_name='numeration',
        ),
    ]
