# Generated by Django 3.1.2 on 2020-10-15 07:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image_picture_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('picture_index',)},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
